name: Scheduled Hemp Data Upload

on:
  schedule:
    # Run at 2:00am CST on the 25th of every month (CST = UTC-6 or -5 with DST)
    - cron: '0 8 25 * *'  # 8am UTC = 2am CST
  workflow_dispatch:      # Allows manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests azure-storage-blob

    - name: Run hemp upload script
      env:
        API_KEY: ${{ secrets.API_KEY }}
        AZURE_CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        RECIPIENT: ${{ secrets.RECIPIENT }}
      run: python "USDA NASS QuickStack Script/hemp_data_upload.py"
